language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm install grunt-cli -g
before_deploy:
- grunt package
deploy:
  provider: npm
  email: canguruhh@mutzl.org
  skip_cleanup: true
  on:
    branch: master
    repo: canguruhh/metaversejs
    tag: latest
  api_key:
    secure: kKwNqEx41iagXhPJ9pWaPhb05H2GePkxrfzLgQ8mk5PEToZfLThYdx+UaynN4iElaG2T25myJ6R1ooKi3DxIJgXEBBwhBo7HBRqzilwoP4ANkAyUPyL0T8bCesQEh4+y2jC3WgUpoP47nQyqCKkhEkvNt287z4hIv9bVlzRxBkoJwLByhVUQFGrKnyMABwKCJz6Wu13R2yC1nV4yk3OutNA0A835jDm6rQC0ZHLTjUcZI0qFzeOcuZz81uWfE3bbEeBJvyYII3RCDzA5PbPxZsFm3O/wRGNFE6j+IeMjtGsKG8l3Zjzhs9oe06jsd5yp3Ofh6AHTwLp9hr7M8lg7fqEnxLe7YQ2gn5mm8bFepBhJkJa9N/nIQWoGD1ua8uF4StwLuReHFARdbMP61VCeYdY/RrGezEyQFjEmEu7JhiP+wLScWQFbgJEHUQ8ixeY12dH0eUwXBixhVVyR8Rnnq/mR8NeS1N/aQMBOB69BpEqNBgfwK0ABnyz/i2xEM/HFniQmwICL5jGTQKDKbRjmrH4QbMlXttQL7PNiNPMGCPFz3xqYCjjHAxkFeuoA3nx2wPWivlDdorBOxs/CXvQDAauO6PjvwN7xGqausOPmvnUGol6JPq+F5bJKWpQwJ8LFcEvbdNAu8lbN5/WhZ2/ONeu+maC9W1UCXe5FwY7xHJQ=
